<!DOCTYPE html>
<html lang="es">

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<meta http-equiv="X-UA-Compatible" content="IE=100" />
	<title>Página no encontrada o de acceso restringido | El Mundo</title>
	<link href="http://estaticos.elmundo.es/em/css/cabecera-pie.css" rel="stylesheet" type="text/css">
	<link href="css/styles.css" rel="stylesheet" type="text/css">
	<meta name="description" content="No hemos podido encontrar esta página o puede que tenga el acceso restringido." />
	<meta name="organization" content="Unidad Editorial Información General S.L.U." />

	<!-- ==== fin metas  ==== -->

	<!-- ==== favicons ==== -->
	<link href="http://estaticos.elmundo.es/favicon.ico" type="image/ico" rel="icon" />
	<link href="http://estaticos.elmundo.es/favicon.ico" type="image/ico" rel="shortcut icon" />

	<!-- ==== links css  ==== -->
	<style type="text/css">
		.hide-text,
		#pagina404 #contenido h2 a strong {
			position: absolute;
			text-indent: -9999px;
		}

		* {
			padding: 0;
			box-sizing: border-box;
		}

		#pagina404 {
			font-family: Arial, sans-serif, helvetica;
			text-align: center;
			padding: auto;
			margin-top: 2.5em;
		}

		@media (min-width: 1024px) {
			#pagina404 {
				margin-top: 8em;
			}
		}

		#pagina404 #contenido {
			width: 100%;
			max-width: 960px;
			height: auto;
			margin: 0 auto;
			margin-bottom: 2em;
		}

		#pagina404 #contenido h1 {
			color: #12466b;
			font-size: 36px;
			padding: 5px 10px;
			text-align: center;
			font-family: Arial, sans-serif, helvetica;
		}

		#pagina404 #contenido h2 p {
			font-size: 16px;
			color: #666;
		}

		#pagina404 #contenido ul {
			list-style-type: none;
			margin: 0 auto;
			width: 95%;
			max-width: 350px;
			margin-bottom: 1.5em;
			display: inline-block;
		}

		@media (min-width: 1024px) {
			#pagina404 #contenido ul {
				max-width: none;
			}
		}

		#pagina404 #contenido li {
			background-color: #1F77B5;
			position: relative;
			margin-bottom: 10px;
		}

		@media (min-width: 1024px) {
			#pagina404 #contenido li {
				float: left;
				margin: 0.5em;
				width: 23%;
			}
		}

		#pagina404 #contenido li a {
			color: white;
			text-decoration: none;
			font-size: 110%;
		}

		#pagina404 #contenido li span {
			line-height: 3.7em;
		}

		#pagina404 #contenido li:hover {
			background-color: #20C0F5;
		}

		#pagina404 #contenido a {
			display: block;
		}

		#pagina404 #contenido #buscador_elmundo fieldset {
			border: 0;
			padding: 0;
		}

		#pagina404 #contenido #buscador_elmundo label {
			width: 365px;
			height: 42px;
			margin-top: 10px;
		}

		#pagina404 #contenido #buscador_elmundo #buscador {
			border: 1px solid #CCCCCC;
			color: #035A89;
			background-color: #F1F1F1;
			display: block;
			font-family: Arial, sans-serif, helvetica;
			font-size: 110%;
			height: 45px;
			padding: 4px 15px;
			width: 95%;
			margin: 0px auto;
			-moz-border-radius: 25px;
			-webkit-border-radius: 25px;
			border-radius: 25px;
			-moz-transition: all 0.3s ease;
			-o-transition: all 0.3s ease;
			-webkit-transition: all 0.3s ease;
			transition: all 0.3s ease;
		}

		#pagina404 #contenido #buscador_elmundo #buscador:focus {
			width: 100%;
		}

		#pagina404 #contenido #formulario {
			position: relative;
			width: 90%;
			max-width: 350px;
			margin: 0 auto;
			display: inline-block;
		}

		#pagina404 #contenido #formulario #buscar {
			position: absolute;
			top: 47px;
			right: 8%;
		}

		#pagina404 #contenido #formulario strong {
			color: #12466b;
			display: block;
			margin-bottom: 12px;
		}
	</style>

</head>

<body id="pagina404">
	<div id="contenido">
		<header class="header">
			<div class="header-wrapper">
				<div class="header-logo elmundo">
					<h2><a href="http://www.elmundo.es" accesskey="p"><strong>Elmundo.es</strong></a></h2>
				</div>

				<div class="header-logo expansion">
					<h2><a href="http://www.expansion.com/" title="Expansion">Expansion</a></h2>
				</div>

				<div class="header-logo yodona">
					<h2> <a href="http://www.elmundo.es/yodona.html" title="Yodona"><span itemprop="name"><strong>Yo Dona</strong></span></a></h2>
				</div>
			</div>
		</header>

		<h1>Página no encontrada</h1>
		<p>Compruebe que ha escrito correctamente la dirección de la página. Si no encuentra lo que busca, puede:</p>
		<ul>
			<li class="portada"><a href="http://www.elmundo.es" accesskey="p" title="Portada"><span>Ir a portada</span></a></li>
			<li class="hemeroteca"><a href="http://www.elmundo.es/hemeroteca/" accesskey="h" title="Hemeroteca"><span>Ir a hemeroteca</span></a></li>
			<li class="mapa"><a href="http://www.elmundo.es/mapadelsitio/" title="Mapa del sitio"><span>Mapa del sitio</span></a></li>
			<li class="contacto"><a href="http://www.elmundo.es/hacemosesto/correo-elmundoes.html" title="Contactar"><span>Contactar</span></a></li>
		</ul>

		<div id="buscador_elmundo">
			<form id="formulario" name="formulario" method="get" action="http://ariadna.elmundo.es/buscador/archivo.html">
				<fieldset id="buscar_elmundo">
					<label for="buscador"><strong>Buscar en ELMUNDO.es </strong>
						<input maxlength="256" name="q" id="buscador" class="" value="" type="text" />
						<input name="buscar" id="buscar" src="http://estaticos.elmundo.es/assets/desktop/master/img/nueva-cabecera/icon/buscar_16_a.png" onclick="this.form.submit()" onkeydown="this.form.submit()" type="image" alt="buscar" title="buscar" />
					</label>
					<input value="" name="b_avanzada" type="hidden" />
				</fieldset>
			</form>
		</div>
	</div>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-scrolldepth/0.6/jquery.scrolldepth.min.js"></script>
	<script src="/js/scripts.js"></script>
</body>

</html>